import { AuthProvider } from '../enums/auth-provider.enum';
import { DeleteStatus } from '../enums/delete-status.enum';
import { RefreshToken } from './refresh-token.entity';
import { LoginHistory } from './login-history.entity';
import { Role } from './role.entity';
import { BaseEntity } from '../../common/entities/base.entity';

export class User extends BaseEntity {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  phone: string;
  avatarUrl: string;
  dateOfBirth: Date;
  gender: string;
  provider: AuthProvider;
  providerId: string;
  emailVerified: boolean;
  emailVerificationToken: string;
  emailVerificationExpiry: Date;
  passwordResetToken: string;
  passwordResetExpiry: Date;
  twoFactorEnabled: boolean;
  twoFactorSecret: string;
  mfaBackupCodes: string[];
  isActive: boolean;
  isLocked: boolean;
  failedLoginAttempts: number;
  lockTime: Date;
  lastLoginAt: Date;
  lastLoginIp: string;
  isDeleted: boolean;
  deletedAt: Date;
  language: string;
  timezone: string;
  notificationEmailEnabled: boolean;
  notificationPushEnabled: boolean;
  notificationInAppEnabled: boolean;
  notificationSecurityEnabled: boolean;
  notificationOrderEnabled: boolean;
  notificationPromotionEnabled: boolean;
  profilePublic: boolean;
  showEmail: boolean;
  showPhone: boolean;
  showActivityStatus: boolean;
  deleteStatus: DeleteStatus;
  deleteRequestedAt: Date;
  fcmToken: string;
  roles: Role[];
  refreshTokens: RefreshToken[];
  loginHistories: LoginHistory[];
}
